dist: bionic

sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
env:
  global:
    - TODAY=`date +"%Y%m%d"`

before_install:
  - sudo sh -c 'echo "deb https://repo.delellis.com.ar bionic bionic" > /etc/apt/sources.list.d/20-pdlib.list'
  - wget -qO - https://repo.delellis.com.ar/repo.gpg.key | sudo apt-key add -
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  - sudo apt update
  - sudo apt-get install libdlib-dev
  - wget https://github.com/goodspb/pdlib/archive/v1.0.tar.gz
  - tar -xzf v1.0.tar.gz
  - pushd pdlib-1.0
  - phpize
  - ./configure --enable-debug && make

script:
  - export NO_INTERACTION=1
  - make test >>phpqatest.$TODAY 2>&1

after_failure:
  - cat phpqatest.$TODAY
